export const ALL_WORKFLOW_COLUMNS = [
  { id: "orderNo", label: "DO Number" },
  { id: "deliveryPurpose", label: "ORDER TYPE (DELIVERY PURPOSE)" },
  { id: "customerType", label: "Customer Type" },
  { id: "orderType", label: "ORDER TYPE" },
  { id: "soNo", label: "SO No." },
  { id: "partySoDate", label: "Party SO Date" },
  { id: "customerName", label: "Customer Name" },
  { id: "itemConfirm", label: "Item Confirm" },
  { id: "productName", label: "Product Name" },
  { id: "uom", label: "UOM" },
  { id: "orderQty", label: "Order Quantity" },
  { id: "altUom", label: "Alternate UOM" },
  { id: "altQty", label: "Alternate Qty (Kg)" },
  { id: "rate", label: "Rate" },
  { id: "oilType", label: "Oil Type" },
  { id: "ratePerLtr", label: "Rate Per Ltr" },
  { id: "ratePer15Kg", label: "Rate Per 15 kg" },
  { id: "rateOfMaterial", label: "Rate Of Material" },
  { id: "totalWithGst", label: "Total Amount With Gst" },
  { id: "transportType", label: "Type Of Transporting" },
  { id: "uploadSo", label: "Upload SO" },
  { id: "contactPerson", label: "Customer Contact Person Name" },
  { id: "whatsapp", label: "Customer Contact Person WhatsApp No." },
  { id: "address", label: "Customer Address" },
  { id: "paymentTerms", label: "Payments Terms" },
  { id: "advanceTaken", label: "Advance Payment to Be Taken" },
  { id: "advanceAmount", label: "Advance Amount" },
  { id: "isBroker", label: "Is This Order Through Broker" },
  { id: "brokerName", label: "Broker Name (IF ORDER THROUGH BROKER)" },
  { id: "deliveryDate", label: "Expected Delivery Date" },
  { id: "qtyToDispatch", label: "Qty to Dispatch" },
  { id: "deliveryFrom", label: "Delivery From" },
  { id: "processid", label: "Process ID" },
  { id: "party_credit_status", label: "Party Credit Status" },
  { id: "dispatch_date_confirmed", label: "Dispatch Date Confirmed" },
  { id: "overall_status_of_order", label: "Overall Status Of Order" },
  { id: "order_confirmation_with_customer", label: "Order Confirmation With Customer" },
  { id: "actual_approval_qty", label: "Actual Approval Qty" },
  { id: "dispatch_from", label: "Dispatch From" },
  { id: "dispatch_planning_user", label: "Dispatch Planning User" },
  { id: "revert_planning_remarks", label: "Revert Planning Remarks" },
  { id: "truck_no", label: "Truck No." },
  { id: "driver_name", label: "Driver Name" },
  { id: "driver_mobile_no", label: "Driver Mobile No." },
  { id: "transporter_name", label: "Transporter Name" },
  { id: "rst_no", label: "RST No." },
  { id: "gross_weight", label: "Gross Weight" },
  { id: "tare_weight", label: "Tare Weight" },
  { id: "net_weight", label: "Net Weight" },
  { id: "actual_qty", label: "Actual Qty" },
  { id: "material_load_user", label: "Material Load User" },
  { id: "weightment_slip_copy", label: "Weightment Slip Copy" },
  { id: "vehicle_no_plate_image", label: "Vehicle No Plate Image" },
  { id: "check_status", label: "Check Status" },
  { id: "vehicle_number", label: "Vehicle Number" },
  { id: "fitness", label: "Fitness" },
  { id: "insurance", label: "Insurance" },
  { id: "tax_copy", label: "Tax Copy" },
  { id: "polution", label: "Polution" },
  { id: "permit1", label: "Permit 1" },
  { id: "permit2_out_state", label: "Permit 2 Out State" },
  { id: "fitness_end_date", label: "Fitness End Date" },
  { id: "insurance_end_date", label: "Insurance End Date" },
  { id: "tax_end_date", label: "Tax End Date" },
  { id: "pollution_end_date", label: "Pollution End Date" },
  { id: "permit1_end_date", label: "Permit 1 End Date" },
  { id: "permit2_end_date", label: "Permit 2 End Date" },
  { id: "actual_qty_dispatch", label: "Actual Qty Dispatch" },
  { id: "product_name_1", label: "Product Name 1" },
  { id: "actual_dispatch_user", label: "Actual Dispatch User" },
  { id: "extra_weight", label: "Extra Weight" },
  { id: "reason_of_difference_in_weight_if_any_speacefic", label: "Reason Of Difference In Weight" },
  { id: "bilty_no", label: "Bilty No." },
  { id: "bilty_image", label: "Bilty Image" },
  { id: "vehicle_image_attachemrnt", label: "Vehicle Image Attachment" },
  { id: "security_guard_status", label: "Security Guard Status" },
  { id: "security_guard_user", label: "Security Guard User" },
  { id: "revert_security_remarks", label: "Revert Security Remarks" },
  { id: "make_invoice_user", label: "Make Invoice User" },
  { id: "invoice_date", label: "Invoice Date" },
  { id: "invoice_copy", label: "Invoice Copy" },
  { id: "bill_type", label: "Bill Type" },
  { id: "bill_amount", label: "Bill Amount" },
  { id: "verification_status", label: "Verification Status" },
  { id: "gate_pass_copy", label: "Gate Pass Copy" },
  { id: "damage_qty", label: "Damage Qty" },
  { id: "damage_status", label: "Damage Status" },
  { id: "credit_note_no", label: "Credit Note No." },
  { id: "vehicleNo", label: "Vehicle No." },
  { id: "invoiceNo", label: "Invoice No." },
  { id: "status", label: "Status" },
]
