export const ALL_WORKFLOW_COLUMNS = [
  { id: "orderNo", label: "DO Number" },
  { id: "deliveryPurpose", label: "ORDER TYPE (DELIVERY PURPOSE)" },
  { id: "customerType", label: "Customer Type" },
  { id: "orderType", label: "ORDER TYPE" },
  { id: "soNo", label: "SO No." },
  { id: "partySoDate", label: "Party SO Date" },
  { id: "customerName", label: "Customer Name" },
  { id: "itemConfirm", label: "Item Confirm" },
  { id: "productName", label: "Product Name" },
  { id: "uom", label: "UOM" },
  { id: "orderQty", label: "Order Quantity" },
  { id: "altUom", label: "Alternate UOM" },
  { id: "altQty", label: "Alternate Qty (Kg)" },
  { id: "oilType", label: "Oil Type" },
  { id: "ratePerLtr", label: "Rate Per Ltr" },
  { id: "ratePer15Kg", label: "Rate Per 15 kg" },
  { id: "rateOfMaterial", label: "Rate Of Material" },
  { id: "totalWithGst", label: "Total Amount With Gst" },
  { id: "transportType", label: "Type Of Transporting" },
  { id: "uploadSo", label: "Upload SO" },
  { id: "contactPerson", label: "Customer Contact Person Name" },
  { id: "whatsapp", label: "Customer Contact Person WhatsApp No." },
  { id: "address", label: "Customer Address" },
  { id: "paymentTerms", label: "Payments Terms" },
  { id: "advanceTaken", label: "Advance Payment to Be Taken" },
  { id: "advanceAmount", label: "Advance Amount" },
  { id: "isBroker", label: "Is This Order Through Broker" },
  { id: "brokerName", label: "Broker Name (IF ORDER THROUGH BROKER)" },
  { id: "deliveryDate", label: "Expected Delivery Date" },
  { id: "qtyToDispatch", label: "Qty to Dispatch" },
  { id: "deliveryFrom", label: "Delivery From" },
  { id: "status", label: "Status" },
]
